export const designTokens = {
  colors: {
    background: '#ffffff',
    surface: '#ffffff',
    surfaceAlt: '#fafafa',
    primary: '#111111',
    secondary: '#f4f4f5',
    muted: '#767676',
    border: '#ececec',
    borderStrong: '#dedede',
    success: '#3dbb72',
    warning: '#d89b2b',
    error: '#e35d5d',
    metricRedBg: '#ffdcde',
    metricBlueBg: '#d9fbff',
    metricGreenBg: '#ddffe2',
    metricPurpleBg: '#eadcff',
    navActive: '#edf0ff',
    navActiveText: '#5f7cff',
    upgrade: '#929292',
    upgradeHover: '#858585',
    focusRing: '#111111',
    scrollbar: '#d7d7d7',
  },
  spacing: {
    1: '4px',
    2: '8px',
    3: '12px',
    4: '16px',
    5: '20px',
    6: '24px',
    8: '32px',
  },
  radius: {
    sm: '4px',
    md: '6px',
    card: '6px',
  },
  shadow: {
    card: '0 1px 2px rgba(16, 24, 40, 0.04)',
    modal: '0 18px 45px rgba(15, 15, 15, 0.18)',
  },
  typography: {
    family: 'Inter, ui-sans-serif, system-ui, sans-serif',
    sizes: {
      xs: '10px',
      sm: '11px',
      base: '12px',
      md: '14px',
      lg: '18px',
    },
  },
} as const;
